[build]
command = "rm -rf $ZOLA_DIR && git clone https://github.com/ppeetteerrs/obsidian-zola $ZOLA_DIR && python $ZOLA_DIR/convert.py && zola --root $ZOLA_DIR build --output-dir public"
publish = "public"

[build.environment]
# Text in landing page button
LANDING_BUTTON = "Explore"
# Site description on landing page
LANDING_DESCRIPTION = "I have nothing but intelligence."
# The Markdown page linked to landing page button (e.g. put home for ./home.md)
LANDING_PAGE = "home"
# Site title on landing page
LANDING_TITLE = "My Second Brain"
PYTHON_VERSION = "3.8"
# Site repo URL
REPO_URL = "https://github.com/deepakness/obs"
# Site title in navbar
SITE_TITLE = "DeepakNess Obs"
# Site URL
SITE_URL = "https://elegant-kare-2e480e.netlify.app/"
# Site Timezone
TIMEZONE = "Asia/Hong_Kong"
# Directory to store zola site files (make sure 
# your site repo does not contain this folder)
ZOLA_DIR = "zola"
ZOLA_VERSION = "0.15.2"
